[functions.livekit-token]
enabled = true
verify_jwt = false
import_map = "./functions/livekit-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/livekit-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/livekit-token/*.html" ]

[functions.create-admin]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-admin/index.ts"