const en = {
  translation: {
    nav: {
      courses: "Courses",
      mentorship: "Mentorship",
      signals: "Signals",
      pricing: "Pricing",
      becomeMentor: "Become a Mentor",
      login: "Log In",
      signup: "Sign Up",
    },
    hero: {
      badge: "System Status — Markets Open",
      title1: "Learn Forex.",
      title2: "Actually Enjoy It.",
      desc: "Real courses, live trading sessions, verified signals, and a community that's actually rooting for you — not just your subscription fee.",
      cta: "Create my account",
    },
    stats: {
      students: "Active Students",
      completion: "Completion Rate",
      courses: "Courses",
      sessions: "Daily Sessions",
    },
    why: {
      eyebrow: "What You Get",
      title: "Everything You Need. Zero Fluff.",
      items: [
        { title: "Charts That Make Sense", desc: "Live forex charts, drawing tools, and multi-timeframe analysis — minus the headache." },
        { title: "Courses Built For Humans", desc: "Bite-sized lessons and video walkthroughs that actually stick, whatever level you're starting from." },
        { title: "Daily Market Recaps", desc: "We read the news so you don't have to. Today's moves, tomorrow's watchlist, zero fluff." },
        { title: "Above Board, Always", desc: "Fully regulated and transparent. Your funds and your data stay exactly where they should — yours." },
        { title: "Mentors, Live", desc: "Watch real trades unfold in real time. Ask anything mid-session. Learn by watching it happen." },
        { title: "Get Rewarded For Showing Up", desc: "Earn points for finishing courses and staying active. Unlock badges, perks, and bragging rights." },
      ],
    },
    about: {
      eyebrow: "Who Are We",
      title: "The Story Behind Blue Chip Trading",
      p1: "It started with a handful of friends, a library table, and way too much ambition. No mentors, no shortcuts — just a shared refusal to stay confused about the markets. Late nights turned into early mornings. We lost money. We got frustrated. Some days none of it made sense. More than once, someone wanted to quit. Nobody did. We stayed locked in until it finally clicked — and once it did, we didn't keep it to ourselves. That's the whole origin story: a brotherhood that turned confusion into skill, and decided to bring others along.",
      p2: "Today, Blue Chip Trading is a global community built on discipline, consistency, and results you can actually point to. What started as a few friends chasing clarity is now a team helping traders everywhere learn, improve, and take control of their own journey — properly, this time.",
    },
    team: {
      eyebrow: "Our Team",
      title: "Meet the Team",
      desc: "At Blue Chip Trading, you're not learning from one person's opinion — you're plugged into a whole crew of professional traders, each obsessing over a different corner of the markets. We took years of trial, error, and hard-earned lessons and turned them into a single, unified path for our students.",
      pillarsTitle: "The Core Pillars:",
      pillars: {
        technical: { title: "Technical Mastery", desc: "Precision entries and exits, sharpened over a decade of staring at charts." },
        fundamental: { title: "Fundamental Insight", desc: "The \"why\" behind the big market moves, broken down in plain English." },
        risk: { title: "Risk Management", desc: "Battle-tested frameworks built to protect your capital above everything else." },
        psychology: { title: "Trading Psychology", desc: "Coaching that builds the patience and discipline of someone who's done this a while." },
        live: { title: "Live Mentorship", desc: "Real-time guidance while the market's actually moving, not after the fact." },
      },
      quote: "\"Our mission is simple: give you the clarity, transparency, and community we wish we'd had when we were starting out.\"",
    },
    pricing: {
      eyebrow: "Simple Pricing",
      title: "One Plan. Everything Included.",
      name: "Everything, One Plan",
      period: "/month",
      features: [
        "Every professional course, unlocked",
        "Live trading sessions with mentors",
        "Verified daily signals",
        "Full community access",
        "Simulated trading environment",
        "Daily market analysis",
      ],
      cta: "Get Started Now",
    },
    steps: {
      eyebrow: "How It Works",
      title: "Up And Running In 3 Steps",
      items: [
        { title: "Sign Up In 2 Minutes", desc: "No card, no catch — just an account and a few minutes of your time." },
        { title: "Pick Your Lane", desc: "Beginner or Pro, you get the full platform either way. Nothing locked behind a paywall." },
        { title: "Learn, Trade, Repeat", desc: "Work through courses, sit in on live sessions, practise on demo, and grow alongside people doing the same thing." },
      ],
      cta: "Create Account →",
    },
    career: {
      title: "Think You've Got What It Takes?",
      desc: "We're always on the lookout for sharp traders to join the mentor team. Prove it, and grow our community with us.",
      cta: "Apply Now →",
      earnings: "Avg Earnings",
      remote: "Remote",
    },
    faq: {
      eyebrow: "Got Questions?",
      title: "Frequently Asked Questions",
      items: [
        { q: "Do I need experience to start?", a: "None at all. Our beginner track starts from zero — what a candlestick is, why spreads exist, all of it." },
        { q: "How much does it cost?", a: "R420 a month, flat. No hidden fees, no surprise tiers. Cancel any time, no questions asked." },
        { q: "Can I try before I buy?", a: "Watch the walkthrough video below for a full look inside. We keep pricing simple with one plan, so trials aren't on the table." },
        { q: "Is my money safe?", a: "We're an education platform, not a broker — we never touch your trading funds. Your subscription only ever covers access to courses and mentorship." },
      ],
      cta: "Join Blue Chip Trading →",
    },
  },
};

const af = {
  translation: {
    nav: {
      courses: "Kursusse",
      mentorship: "Mentorskap",
      signals: "Seine",
      pricing: "Pryse",
      becomeMentor: "Word 'n Mentor",
      login: "Meld Aan",
      signup: "Registreer",
    },
    hero: {
      badge: "Stelselstatus — Markte Oop",
      title1: "Leer Forex.",
      title2: "Geniet Dit Eintlik.",
      desc: "Egte kursusse, regstreekse handelsessies, geverifieerde seine, en 'n gemeenskap wat werklik agter jou staan — nie net jou intekengeld nie.",
      cta: "Skep my rekening",
    },
    stats: {
      students: "Aktiewe Studente",
      completion: "Voltooiingskoers",
      courses: "Kursusse",
      sessions: "Daaglikse Sessies",
    },
    why: {
      eyebrow: "Wat Jy Kry",
      title: "Alles Wat Jy Nodig Het. Geen Nonsens.",
      items: [
        { title: "Grafieke Wat Sin Maak", desc: "Regstreekse forex-grafieke, tekengereedskap, en multi-tydraamontleding — sonder die kopseer." },
        { title: "Kursusse Vir Mense Gebou", desc: "Klein, verteerbare lesse en video's wat regtig vasklem, ongeag jou vlak." },
        { title: "Daaglikse Markopsommings", desc: "Ons lees die nuus sodat jy dit nie hoef te doen nie. Vandag se bewegings, môre se kyklys." },
        { title: "Altyd Eerlik", desc: "Volledig gereguleer en deursigtig. Jou fondse en data bly presies waar dit hoort — joune." },
        { title: "Mentors, Regstreeks", desc: "Kyk hoe regte transaksies regstreeks ontvou. Vra enigiets tydens die sessie." },
        { title: "Word Beloon Vir Opdaag", desc: "Verdien punte vir die voltooiing van kursusse en aktief bly. Ontsluit wenkkaarte en voordele." },
      ],
    },
    about: {
      eyebrow: "Wie Is Ons",
      title: "Die Storie Agter Blue Chip Trading",
      p1: "Dit het begin met 'n handjievol vriende, 'n biblioteektafel, en te veel ambisie. Geen mentors, geen kortpaaie nie — net 'n gedeelde weiering om verward te bly oor die markte. Laat nagte het vroeë oggende geword. Ons het geld verloor. Ons het gefrustreerd geraak. Party dae het niks sin gemaak nie. Meer as een keer wou iemand ophou. Niemand het nie. Ons het aangehou tot dit uiteindelik geklik het — en toe dit gebeur het, het ons dit nie vir onsself gehou nie.",
      p2: "Vandag is Blue Chip Trading 'n wêreldwye gemeenskap gebou op dissipline, konsekwentheid, en resultate wat jy werklik kan wys. Wat begin het as 'n paar vriende wat na duidelikheid gejaag het, is nou 'n span wat handelaars regoor die wêreld help om te leer, te verbeter, en beheer oor hul eie reis te neem.",
    },
    team: {
      eyebrow: "Ons Span",
      title: "Ontmoet Die Span",
      desc: "By Blue Chip Trading leer jy nie van net een persoon se mening nie — jy's gekoppel aan 'n hele span professionele handelaars, elkeen gefokus op 'n ander hoek van die mark. Ons het jare se ondervinding omgeskep in een verenigde pad vir ons studente.",
      pillarsTitle: "Die Kernpilare:",
      pillars: {
        technical: { title: "Tegniese Bemeestering", desc: "Presiese in- en uittredes, verskerp oor 'n dekade se grafiek-analise." },
        fundamental: { title: "Fundamentele Insig", desc: "Die \"hoekom\" agter groot markbewegings, verduidelik in eenvoudige taal." },
        risk: { title: "Risikobestuur", desc: "Beproefde raamwerke gebou om jou kapitaal bo alles te beskerm." },
        psychology: { title: "Handelsielkunde", desc: "Afrigting wat geduld en dissipline bou soos iemand wat dit al 'n ruk doen." },
        live: { title: "Regstreekse Mentorskap", desc: "Regstreekse leiding terwyl die mark werklik beweeg, nie agterna nie." },
      },
      quote: "\"Ons missie is eenvoudig: gee jou die duidelikheid, deursigtigheid, en gemeenskap wat ons wens ons gehad het toe ons begin het.\"",
    },
    pricing: {
      eyebrow: "Eenvoudige Pryse",
      title: "Een Plan. Alles Ingesluit.",
      name: "Alles, Een Plan",
      period: "/maand",
      features: [
        "Elke professionele kursus, ontsluit",
        "Regstreekse handelsessies met mentors",
        "Geverifieerde daaglikse seine",
        "Volle gemeenskapstoegang",
        "Gesimuleerde handelsomgewing",
        "Daaglikse markontleding",
      ],
      cta: "Begin Nou",
    },
    steps: {
      eyebrow: "Hoe Dit Werk",
      title: "Binne 3 Stappe Aan Die Gang",
      items: [
        { title: "Registreer In 2 Minute", desc: "Geen kaart, geen vangplek nie — net 'n rekening en 'n paar minute van jou tyd." },
        { title: "Kies Jou Baan", desc: "Beginner of Pro, jy kry die volle platform in elk geval." },
        { title: "Leer, Handel, Herhaal", desc: "Werk deur kursusse, woon regstreekse sessies by, oefen op demo, en groei saam met ander." },
      ],
      cta: "Skep Rekening →",
    },
    career: {
      title: "Dink Jy Het Wat Nodig Is?",
      desc: "Ons soek altyd skerp handelaars om by die mentorspan aan te sluit. Bewys dit, en groei ons gemeenskap saam met ons.",
      cta: "Doen Aansoek →",
      earnings: "Gem. Verdienste",
      remote: "Afgeleë",
    },
    faq: {
      eyebrow: "Vrae?",
      title: "Gereelde Vrae",
      items: [
        { q: "Het ek ondervinding nodig om te begin?", a: "Glad nie. Ons beginnersbaan begin van nul af — wat 'n kers is, hoekom spreads bestaan, alles." },
        { q: "Hoeveel kos dit?", a: "R420 per maand, plat tarief. Geen verskuilde fooie nie. Kanselleer enige tyd." },
        { q: "Kan ek probeer voor ek koop?", a: "Kyk na die deurloop-video hieronder vir 'n volledige kykie. Ons hou pryse eenvoudig met een plan." },
        { q: "Is my geld veilig?", a: "Ons is 'n opvoedkundige platform, nie 'n makelaar nie — ons raak nooit jou handelsfondse aan nie." },
      ],
      cta: "Sluit Aan By Blue Chip Trading →",
    },
  },
};

export { en, af };